version: 0.2.25.{build}
skip_tags: true
environment:
  matrix:
    - appveyor_build_worker_image: Visual Studio 2017
      configuration: Release
      platform: x86
    - appveyor_build_worker_image: Visual Studio 2017
      configuration: Release(x64)
      platform: x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a ManiacEditor-Beta-Generations-v%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\ManiacEditor\bin\Release\* %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\ManiacEditor\bin\Release\Resources %APPVEYOR_BUILD_FOLDER%\LICENSE
artifacts:
 - path: 'ManiacEditor\bin\Release'
   name: '$(appveyor_project_name) $(appveyor_build_version) [x86]'
   type: zip
 - path: 'ManiacEditor\bin\Release(x64)'
   name: '$(appveyor_project_name) $(appveyor_build_version) [x64]'
   type: zip