version: 1.0.0.{build}
image: Visual Studio 2017
skip_tags: true
environment:
  matrix:
    - BUILD: Universal (x86 / x64) (To Download Click Here and Then click Artifacts) ||| 
      appveyor_build_worker_image: Visual Studio 2017
      configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - cd RSDK-Reverse
  - nuget restore "RSDK Reverse.sln"
build:
  verbosity: minimal
  project: ManiacEditor
artifacts:
 - path: 'ManiacEditor\bin\Release(x86)'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[x86]'
   type: zip
 - path: 'ManiacEditor\bin\Release(x64)'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[x64]' 
   type: zip
 - path: 'ManiacEditor\bin\Release'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[AnyCPU]' 
   type: zip
