version: 1.0.0.{build}
image: Visual Studio 2017
skip_tags: true
environment:
  matrix:
    - Version: x86 (To Download: Click 'Artifacts' after clicking this link)_____________________________________________________
      appveyor_build_worker_image: Visual Studio 2017
      configuration: Release
      platform: x86

    - Version: x64 (To Download: Click 'Artifacts' after clicking this link)_____________________________________________________
      appveyor_build_worker_image: Visual Studio 2017
      configuration: Release
      platform: x64

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
 - path: 'ManiacEditor\bin\Release(x86)'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[x86]'
   type: zip
 - path: 'ManiacEditor\bin\Release(x64)'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[x64]' 
   type: zip
