version: 0.2.25.{build}
skip_tags: true
image: Visual Studio 2017
configuration:
- x64 Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a ManiacEditor-Beta-Generations-x64-v%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\ManiacEditor\bin\Release(x64)\* %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\ManiacEditor\bin\Release(x64)\Resources %APPVEYOR_BUILD_FOLDER%\LICENSE
artifacts:
- path: ManiacEditor-Beta-Generations-x64-v%APPVEYOR_BUILD_VERSION%.zip
  name: ManiacEditor-Generations-x64