version: 1.0.0.{build}
shallow_clone: true
image: Visual Studio 2019
skip_tags: true
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
environment:
  matrix:
    - BUILD: Universal (x86 / x64) (To Download Click Artifacts) ||||---------------------------------------
      appveyor_build_worker_image: Visual Studio 2019
      configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore
build:
  verbosity: minimal
  project: ManiacEditor.sln
artifacts:
 - path: 'ManiacEditor\bin\Release'
   name: 'ManiacEditor-Generations-BETA-$(appveyor_build_version)[AnyCPU]' 
   type: zip
